project_name     = "nextime-app"
aws_region       = "us-east-1"
account_id       = "383349724220" 
package_type     = "Image"
memory_size      = "512"
timeout          = "30"
lambda_image_tag = "latest"

ses_sender_email     = "framenextime@gmail.com" 
cognito_user_pool_id = "us-east-1_Oczuuo3wx" 
