name: Test and Deploy to AWS

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  IMAGE_TAG: latest

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ------------------------------
      # 1️⃣ Checkout repository
      # ------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ------------------------------
      # 2️⃣ Setup Terraform
      # ------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # ------------------------------
      # 3️⃣ Cache Terraform providers
      # ------------------------------
      - name: Cache Terraform providers
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform.d/plugin-cache
            infra/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('infra/**/*.tf*') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      # ------------------------------
      # 4️⃣ Configure AWS (OIDC + IAM Role)
      # ------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-action-role
          aws-region: ${{ env.AWS_REGION }}

      # ------------------------------
      # 5️⃣ Terraform – validação e criação do ECR
      # ------------------------------
      - name: Terraform Format
        run: terraform fmt -check -diff || true
        working-directory: infra

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra

      - name: Terraform Apply (ECR)
        id: tf_apply_ecr
        run: |
          terraform apply -target=aws_ecr_repository.lambda_auth_repo \
                          -target=aws_ecr_repository.lambda_registration_repo \
                          -target=aws_ecr_repository.lambda_get_user_repo \
                          -target=aws_ecr_repository.lambda_list_users_repo \
                          -auto-approve

          # Captura os URIs do ECR
          echo "LAMBDA_AUTH_ECR_URI=$(terraform output -raw ecr_lambda_auth_url)" >> $GITHUB_ENV
          echo "LAMBDA_REGISTRATION_ECR_URI=$(terraform output -raw ecr_lambda_registration_url)" >> $GITHUB_ENV
          echo "LAMBDA_GET_USER_ECR_URI=$(terraform output -raw ecr_lambda_get_user_url)" >> $GITHUB_ENV
          echo "LAMBDA_LIST_USERS_ECR_URI=$(terraform output -raw ecr_lambda_list_users_url)" >> $GITHUB_ENV
        working-directory: infra

      # ------------------------------
      # 6️⃣ Docker Build & Push
      # ------------------------------
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login no Amazon ECR
        run: |
          # Extrair apenas o host do ECR
          AUTH_ECR_HOST=$(echo ${{ env.LAMBDA_AUTH_ECR_URI }} | cut -d'/' -f1)
          REGISTRATION_ECR_HOST=$(echo ${{ env.LAMBDA_REGISTRATION_ECR_URI }} | cut -d'/' -f1)

          # Login Docker
          aws ecr get-login-password --region ${{ env.AWS_REGION }} \
            | docker login --username AWS --password-stdin $AUTH_ECR_HOST
          aws ecr get-login-password --region ${{ env.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ env.LAMBDA_REGISTRATION_ECR_URI }}
          aws ecr get-login-password --region ${{ env.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ env.LAMBDA_GET_USER_ECR_URI }}
          aws ecr get-login-password --region ${{ env.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ env.LAMBDA_LIST_USERS_ECR_URI }}
 

      - name: Build, Tag e Push Lambda Authorizer
        run: |
          docker build -t lambda-auth src/lambda_auth/
          docker tag lambda-auth:latest ${{ env.LAMBDA_AUTH_ECR_URI }}:latest
          docker push ${{ env.LAMBDA_AUTH_ECR_URI }}:latest

      - name: Build, Tag e Push Lambda Registration
        run: |
          docker build -t lambda-registration src/lambda_registration/
          docker tag lambda-registration:latest ${{ env.LAMBDA_REGISTRATION_ECR_URI }}:latest
          docker push ${{ env.LAMBDA_REGISTRATION_ECR_URI }}:latest

      - name: Build, Tag e Push Lambda Get User
        run: |
          docker build -t lambda-get-user src/lambda_get_user/
          docker tag lambda-get-user:latest ${{ env.LAMBDA_GET_USER_ECR_URI }}:latest
          docker push ${{ env.LAMBDA_GET_USER_ECR_URI }}:latest

      - name: Build, Tag e Push Lambda List Users
        run: |
          docker build -t lambda-list-users src/lambda_list_users/
          docker tag lambda-list-users:latest ${{ env.LAMBDA_LIST_USERS_ECR_URI }}:latest
          docker push ${{ env.LAMBDA_LIST_USERS_ECR_URI }}:latest

      # ------------------------------
      # 7️⃣ Terraform – Deploy Lambdas
      # ------------------------------
      - name: Terraform Plan para Deploy
        run: |
          terraform plan -out=tfplan
        working-directory: infra

      - name: Terraform Apply (Deploy Lambdas)
        run: terraform apply -auto-approve tfplan
        working-directory: infra
